# Generated by Django 2.0 on 2019-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('sex', models.CharField(max_length=50, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='家庭住址')),
                ('enter_date', models.DateField(verbose_name='入学时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
    ]
